version: '3'

services:
  ninjaone-agent:
    build:
      context: .
      args:
        - NINJA_INSTALLER_URL=${NINJA_INSTALLER_URL}
    container_name: ninjaone-agent
    network_mode: 'host'
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - SYS_RESOURCE
      - SYS_TIME
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      # Host monitoring paths
      - /proc:/host/proc:ro
      - /:/host:ro
      # System logs
      - /var/log:/var/log:ro
      # Proxmox specific logs
      - /var/log/pve:/var/log/pve:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/run
      - /var/log/journal
    environment:
      - HOST_MOUNT=/host
      - container=docker
      - SYSTEMD_IGNORE_CHROOT=1
